apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-z6hn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-z6hn
    app.kubernetes.io/part-of: tkwch-fix-0075-0062-app
  name: devfile-sample-z6hn
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-z6hn
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-z6hn
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0062-tenant/tkwch-fix-0075-0062-app/devfile-sample-z6hn@sha256:a94bf5ed67dc9106e072a4475c62c9d12f44d1a82433c77bf3fc20aa75592b4f
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
